title: "TAHub"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S1-CS2103T-T16-2/tp3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
